version: '3.9'
services:
  app:
    container_name: countries-telegram-bot
    build: .
    restart: on-failure
    volumes:
      - .:/app/cmd
    depends_on:
      - db
    networks:
      - countries-bot

  db:
    image: postgres:latest
    container_name: countries-postgres
    env_file:
      - app.env
    environment:
      - POSTGRES_USER=$${USERNAME}
      - POSTGRES_PASSWORD=$${PASSWORD}
      - POSTGRES_DB=$${DBNAME}
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    networks:
      - countries-bot

volumes:
  pgdata:

networks:
  countries-bot:
    driver: bridge