telegram-bot:
  token: 6113285591:AAFDPnm0AgdnT3m8KtSYD-atDRpySK2p8uI
  update-offset: 0
  update-timeout: 60

rest-countries-api:
  baseUrl: https://restcountries.com/v3.1/

postgres:
    host: localhost
    port: 5432
    username: root
    password: root
    dbname: countries-pg